### ISSUE TITLE
Hyperref in amsmath's \text doesn't get hyperlinked

### ISSUE THREAD

**Issue by cpitclaudel** [ho-tex/hyperref#13]
This is a follow-up to https://tex.stackexchange.com/questions/310877/why-does-usepackageamsmath-break-hyperref-in-textnormal :) In the following example, when using xelatex, the first hyperlink is properly activated, but not the second one:

```latex
\documentclass{article}

\usepackage{amsmath} % Removing this makes the second link work
\usepackage{hyperref}

\begin{document}
  \hyperref[abc-def]{link} % This link works
  \(\textnormal{\hyperref[abc-def]{link}}\) % But not this one
  \label{abc-def} Target
\end{document}
```

Removing amsmath activates both links.

Thanks!

**Comment by davidcarlisle** [comment]
@cpitclaudel This affects xetex and dvipdfm driver options, I think it is enough to add


```
\makeatletter
\ifx\c@Hy@AnnotLevel\@undefined\else
\def\Hy@BeginAnnot#1{%
  \global\advance\c@Hy@AnnotLevel\@ne
  \ifnum\c@Hy@AnnotLevel=\@ne
    #1%
 \fi
}
\def\Hy@EndAnnot{%
  \ifnum\c@Hy@AnnotLevel=\@ne
    \Hy@endcolorlink
    \@pdfm@mark{eann}%
  \fi
  \global\advance\c@Hy@AnnotLevel\m@ne
}
\fi
\makeatother
```
after loading hyperref.

this uses primitive `\global\advance\c@foo` instead of `\stepcounter{foo}` and so avoids `amsmath` making `\stepcounter` "safe" or equivalently change those two macros in hxetex.def and hdvipdfm.def.

**Comment by cpitclaudel** [comment]
Neat, thanks!

**Comment by davidcarlisle** [comment]
hyperref v6.83p uploaded to CTAN
