### ISSUE TITLE
Bad interaction with portuges babel in captions

### ISSUE THREAD

**Issue by norbusan** [ho-tex/hyperref#39]
Dear all,
down at Debian we got a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862497) that using hyperref and portuges babel breaks captions. A MNWE is:
```
\documentclass{article}
\usepackage[portuges]{babel}
\usepackage[pdftex,plainpages=false]{hyperref}
\begin{document}
\begin{table}
\caption{Table "title" }
% this works: \caption{Table title }
\end{table}
\end{document}
```
The problem is in the handling of ", the error message is:
```
! Extra \endcsname.
\language@active@arg" ...@"@\string #1@\endcsname 
                                                  \fi 
l.6 \caption{Table "title" }
```
I'm not sure if that can be fixed in hyperref or in portuges, but I thought I ask.

Thanks

Norbert

**Comment by davidcarlisle** [comment]
Hi hyperref can probably take more precautions over active characters here but ultimately I would class this as a user error.

babel (inheriting from the earliest german.sty packages I think) has always assumed it was safe to use " as a shorthand preciously because it should never be used as literal input character the markup should be

```
``title''
or ''title''

```

or whatever the quote convention should be.  

Even in plain text  outside captions, where hyperref is not involved at all, with this babel setup I don't think 

`x "title" y `

works you get no error but white space is wrong (I assume) as you lose the space before y as " is a macro looking for "<

**Comment by norbusan** [comment]
Argg, indeed, yes, agreed. Sorry for the noise. I completely forgot that " is active (used to write umlauts directly nowadays).

Best

Norbert

**Comment by osamuaoki** [comment]
Looks like this was dblatex problem
It was fixed there
