### ISSUE TITLE
UTF8 in TextField's value

### ISSUE THREAD

**Issue by kberry** [ho-tex/hyperref#5]
(reposted from https://puszcza.gnu.org.ua/bugs/index.php?204, author  	Thorsten <zittho>)

Hi. I have the following packages:

\usepackage[ngerman]{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

When I create a textfield with

\TextField[name=test, value=Groß]{test}

the value shows as "GroT1ss"

How can I fix this?

**Comment by u-fischer** [comment]
The problem is not really related to utf8, \ss and similar commands break too. 

Imho the problem is that the field value is not passed through `\pdfstringdef`. This is seems to solve the problem (but it is not very thoroughly tested):

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{textcomp}
\usepackage[T1]{fontenc}
\usepackage{hyperref}
\makeatletter
\define@key{Field}{value}{%
  \Hy@pdfstringdef\Fld@value{#1}%new
  %\def\Fld@value{#1}%old
}
\makeatother
\begin{document}

When I create a textfield with
\TextField[name=test, value=Größü€\ss]{test}
\end{document}
```

![pdfstringdef](https://cloud.githubusercontent.com/assets/4047173/15465154/6d2a67a2-20d3-11e6-9412-26c25d08cc81.PNG)

**Comment by davidcarlisle** [comment]
@u-fischer  thanks that looks about right, I'd seen it was unrelated to input encoding but not traced the interesting path the various escape mechanisms take.

**Comment by davidcarlisle** [comment]
hyperref v6.83p uploaded to CTAN
