### ISSUE TITLE
pdf documentation dated September 2018 has broken internal links ?

### ISSUE THREAD

**Issue by jfbu** [ho-tex/hyperref#75]
On one computer with TL2018 updated a few days back texdoc hyperref opens up a file `manual.pdf` with date `September 2018`, and internal hyperlinks allowing to navigate to the README and to the hyperref.dtx incorporated source seem to be broken (at least in Adobe Reader on Mac OS).

On another MAC, with a slightly older TL2018, the `manual.pdf` is date `January 2017`. When I click in the bookmark panel on the triangle next to "Hyperref manual", I see a README link and a "Sources: hyperref.dtx" link and clicking this latter, a file `hyperref.pdf` is opened containing the commented codes of various files in this bundle.

**Comment by jfbu** [comment]
update: some links do work. But `README` and `hyperref.dtx` don't.

**Comment by davidcarlisle** [comment]
Oops thanks for the report. essentially README(.pdf) was an extension manual for all the things Heiko added (and self documented as being planned to be added to the main manual one day) In the last release I incorporated the bulk of the README into the main manual so README is now just a more traditional plan text (actually markdown) README so that link should go.

the broken link to the documented sources seems to be because they are not there, my build script makes them but apparently doesn't include them in the zip, I'll check, thanks
