### ISSUE TITLE
Hyperref + xr problem 

### ISSUE THREAD

**Issue by alessandroandretta** [ho-tex/hyperref#82]

**Comment by alessandroandretta** [comment]
Since the last update the xr package (contained in "tools") seems to conflict with hyperref.
Below there are two files: the main one foo.tex and an external one aaa.tex.
If you compile aaa.tex with hyperref, the cross-ref with foo.tex are ruined.
This might be a problem of the xr package, rather than of the hperref package

%%%%aaa.tex%%%%%%
\documentclass{article}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{corollary}[theorem]{Corollary}
%\usepackage{hyperref} %Activate this for the bug
\title{External document}
\author{}
\begin{document}
\maketitle
\section{Beginnings}\label{sec:beginnings}
\begin{theorem}\label{th:main}
This is the main theorem.
\end{theorem}
\section{Consequences}\label{sec:consequences}
Using Theorem~\ref{th:main} we obtain:
\begin{corollary}\label{cor:trivial}
This is a trivial corollary.
\end{corollary}
\end{document}  
%%%%%%

%%%%foo.tex%%%%%
\documentclass{article}
\usepackage{xr} 
\externaldocument[A-]{aaa}
\title{Main document}
\author{}
\begin{document}
\maketitle
\section{Test}
In Section~\ref{A-sec:beginnings} we stated the main result, Theorem~\ref{A-th:main}, and in Section~\ref{A-sec:consequences} we obtained Corollary~\ref{A-cor:trivial}.
\end{document}  
%%%%%%%%%%%%%%%%%%

**Comment by davidcarlisle** [comment]
I agree it doesn't work, I'll see what I can do, however I don't think the
xr update changed thins, I just tried with texlive 2017 and 2016 and got
the same result.

You get a better result if you use hyperref in both documents, and use
xr-hyper rather than xr.

There has been a longstanding (since before latex2e...) issue to try to
combine xr and xr-hper, but it's tricky as the internal data structures for
cross referencing change radically if hyperref is used. The case you have
here with a document not using hyperref referencing one that does use
hyperref is particularly tricky as the reference needs to "understand" the
hyperref data without loading hyperref in that case.

David

**Comment by alessandroandretta** [comment]
I tried xr-hyper and that solved my problem. Thanks a lot for the suggestion, I really appreciate your help! 
I beg to differ though on the update issue. I am regularly upgrading TeXLive 2018 on my Mac using the TeXLive manager. A few weeks ago the "tools" package came on the list to be updated, so I hit the button "Update all". Since then I hit the roadblock, so my only way-out was to downgrade the "tools" package to the previous version. Now with your solution at hand, I can safely update TeXLive 2018!

**Comment by u-fischer** [comment]
I tried your example with texlive 2017 and texlive 2018 and it fails (quite expected) in both. No update changed here anything. Also simply using xr-hyper in the main document doesn't resolve the problem. On need to use hyperref in both files.
